package io.wootlab.micronaut.initializr.model;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Feature {
    security_session("security-session"),
    picocli("picocli"),
    spock("spock"),
    micrometer_ganglia("micrometer-ganglia"),
    rabbitmq("rabbitmq"),
    hibernate_gorm("hibernate-gorm"),
    graphql("graphql"),
    hibernate_jpa("hibernate-jpa"),
    jib("jib"),
    springloaded("springloaded"),
    jrebel("jrebel"),
    mongo_gorm("mongo-gorm"),
    micrometer_elastic("micrometer-elastic"),
    micrometer_kairos("micrometer-kairos"),
    asciidoctor("asciidoctor"),
    micrometer_atlas("micrometer-atlas"),
    kafka("kafka"),
    aws_api_gateway_graal("aws-api-gateway-graal"),
    aws_api_gateway("aws-api-gateway"),
    micrometer_appoptics("micrometer-appoptics"),
    mongo_reactive("mongo-reactive"),
    micrometer_new_relic("micrometer-new-relic"),
    annotation_api("annotation-api"),
    micrometer_prometheus("micrometer-prometheus"),
    micrometer_jmx("micrometer-jmx"),
    postgres_reactive("postgres-reactive"),
    micrometer_datadog("micrometer-datadog"),
    netflix_ribbon("netflix-ribbon"),
    application("application"),
    cassandra("cassandra"),
    netflix_hystrix("netflix-hystrix"),
    micrometer_cloudwatch("micrometer-cloudwatch"),
    file_watch("file-watch"),
    redis_lettuce("redis-lettuce"),
    config_consul("config-consul"),
    jdbc_hikari("jdbc-hikari"),
    jdbc_dbcp("jdbc-dbcp"),
    micrometer_azure_monitor("micrometer-azure-monitor"),
    netflix_archaius("netflix-archaius"),
    elasticsearch("elasticsearch"),
    micrometer_humio("micrometer-humio"),
    micrometer_statsd("micrometer-statsd"),
    tracing_jaeger("tracing-jaeger"),
    micrometer_influx("micrometer-influx"),
    logback("logback"),
    micrometer_graphite("micrometer-graphite"),
    kafka_streams("kafka-streams"),
    neo4j_bolt("neo4j-bolt"),
    swagger_groovy("swagger-groovy"),
    junit("junit"),
    graal_native_image("graal-native-image"),
    micrometer_wavefront("micrometer-wavefront"),
    swagger_java("swagger-java"),
    micrometer_signalfx("micrometer-signalfx"),
    tracing_zipkin("tracing-zipkin"),
    discovery_eureka("discovery-eureka"),
    discovery_consul("discovery_-onsul"),
    jdbc_tomcat("jdbc-tomcat"),
    liquibase("liquibase"),
    micrometer("micrometer"),
    security_jwt("security-jwt"),
    http_server("http-server"),
    flyway("flyway"),
    micrometer_stackdriver("micrometer-stackdriver"),
    management("management"),
    spek("spek"),
    kubernetes("kubernetes"),
    swagger_kotlin("swagger-kotlin"),
    kotlintest("kotlintest"),
    http_client("http-client"),
    micrometer_dynatrace("micrometer-dynatrace"),
    neo4j_gorm("neo4j-gorm");

    private String value;
}
